[package]
name = "flatten"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.6"
lyon_path = "1.0.7"

[dev-dependencies]
criterion = "0.3"
usvg = "0.15.0"

[[bench]]
name = "bench"
harness = false
