[package]
name = "flatten"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.6"
kurbo = "0.11.1"
lyon_path = "1.0.7"
svg_fmt = "0.4.4"
usvg = "0.36.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false

[features]
fma = []
stats = []
approx = []
