[package]
name = "flatten"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.6"
lyon_path = "1.0.7"
usvg = { version = "0.15.0", optional = true }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false

[features]
testing = ["usvg"]
fma = []
