[package]
name = "wgslp_cli"
version = "0.1.0"
edition = "2021"
workspace = ".."

[[bin]]
name = "wgslp"
path = "src/main.rs"

[dependencies]
wgslp = { path = "../lib" }
walkdir = "2"
clap = { version = "3.2.16", features = ["derive"] }
toml = "0.4.5"
serde = "1.0.142"
serde_derive = "1.0.142"
