[package]
name = "tiling"
version = "0.1.0"
authors = ["Nicolas Silva <nical@fastmail.com>"]
edition = "2018"

[dependencies]
lyon_path = "0.14"
svg_fmt = "0.4.1"
usvg = "0.4"
time = "0.1.42"
ordered-float = "1.0.2"

[profile.release]
debug=true
