[package]
name = "stats"
version = "0.1.0"
edition = "2021"
authors = ["Nicolas Silva"]
license = "MIT OR Apache-2.0"

[dependencies]
core = { path = "../../core" }
debug_overlay = { version = "0.2.2", features = ["wgpu"] }

